# Generated by Django 5.2.1 on 2026-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('CPU', 'CPU'), ('MEMORY', 'MEMORY'), ('DISK', 'DISK'), ('NETWORK', 'NETWORK')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
