# Generated by Django 5.2.1 on 2026-05-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_anomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probable_cause', models.TextField()),
                ('impacted_service', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.anomaly')),
            ],
        ),
    ]
