# Generated by Django 5.2.1 on 2026-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INVESTIGATING', 'INVESTIGATING'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=50),
        ),
    ]
